### PR TITLE
build with Gitlab CI

### PR DESCRIPTION
**Pull request by hannesa2**

### CODE REVIEW

**Comment by hannesa2** [comment]
Here is the first finding
image

**Comment by hannesa2** [comment]
I solve it in #9 https://github.com/open-keychain/openpgp-api/pull/9/commits/142705cb8f7d4332b95f9c572aa05fab9b7f9c1b

**Comment by hannesa2** [comment]
It looks like, you have to enable github actions for this repo.
When I make this PR in my repo, the actions runs properly https://github.com/hannesa2/openpgp-api/pull/1 

image

**Comment by Valodim** [comment]
Thanks!

**Pull request merged**
